// AUTO-GENERATED by scripts/gen-kotlin.mjs from src/strings.json — do not edit by hand.
// Regenerate via `npm run build`. See README.md "Releasing a new version".

package com.curio.copy

public object CurioCopy {
    public object LegacyCardStatusLabels {
        public val all: Map<String, String> = mapOf(
            "draft" to "Draft",
            "in_stock" to "In stock",
            "listed" to "Listed",
            "sold" to "Sold",
            "reconciled" to "Reconciled",
            "returned" to "Returned",
            "archived" to "Archived",
        )
    }

    public object PhysicalCardLifecycleLabels {
        public val all: Map<String, String> = mapOf(
            "NEEDS_ID_REVIEW" to "Needs ID review",
            "NEEDS_CONDITION" to "Needs condition",
            "NEEDS_DECISION" to "Needs decision",
            "READY_TO_LIST" to "Ready to list",
            "EBAY_DRAFT" to "Draft created",
            "LISTED" to "Listed",
        )
    }

    public object AttentionQueueCtas {
        public val all: Map<String, String> = mapOf(
            "NEEDS_ID_REVIEW" to "Review",
            "NEEDS_CONDITION" to "Assess",
            "NEEDS_DECISION" to "Decide",
            "READY_TO_LIST" to "List",
        )
    }

    public object RouteLabels {
        public val all: Map<String, String> = mapOf(
            "list_single" to "List individually",
            "bundle" to "Bundle",
            "bulk" to "Bulk",
            "hold" to "Hold",
            "grade_review" to "Consider grading",
            "restoration_review" to "Restoration review",
            "do_not_list" to "Don't list",
        )
    }

    public object RouteReasonLabels {
        public val all: Map<String, String> = mapOf(
            "below_bulk_floor" to "Fees and postage absorb the value",
            "net_below_minimum" to "Nets less than your minimum",
            "grade_worth_reviewing" to "Worth checking graded comps",
            "thin_market" to "Not enough recent sales to price it confidently",
            "bundle_lot_available" to "You hold enough similar cards to make a lot",
            "sound_single_listing" to "Sells well on its own",
        )
    }

    public object AlternativeReasonLabels {
        public val all: Map<String, String> = mapOf(
            "net_negative_after_costs" to "Net negative after fees and postage",
            "bundle_shares_postage" to "Bundling shares one postage",
            "list_ungraded_instead" to "List it ungraded instead",
            "list_now_accept_slower" to "List now and accept a slower sale",
            "list_alone_instead" to "List it on its own instead",
        )
    }

    public object DegradedReasonLabels {
        public val all: Map<String, String> = mapOf(
            "no_sale_count" to "No recent sales data to draw on",
            "fees_unknown" to "Your fee settings weren't available",
            "compatible_count_unknown" to "We didn't check your other cards",
        )
    }

    public object DecisionUnavailableLabels {
        public val all: Map<String, String> = mapOf(
            "identity_unresolved" to "We couldn't identify this card",
            "no_market_value" to "No recent sales to price this from",
            "pricing_unavailable" to "Pricing is unavailable right now — try again shortly",
        )
    }

    public object AssumptionLabels {
        public val all: Map<String, String> = mapOf(
            "channel" to "Assumed you'll sell on eBay",
            "seller_type" to "Assumed you sell as a private seller",
            "vat_registered" to "Assumed you're not VAT-registered",
            "condition" to "Assumed near mint condition",
            "postage" to "Assumed standard postage",
            "packaging" to "Assumed standard packaging",
            "tax_rate" to "Assumed the basic-rate tax band",
            "cost_basis" to "Assumed you haven't bought it yet",
        )
    }

    public object EditionAmbiguityLabels {
        public val all: Map<String, String> = mapOf(
            "first_edition_shadowless_unlimited" to "This price can't tell 1st Edition, Shadowless and Unlimited apart — they can differ by a lot. Check the stamp and the shadow before you sell.",
            "first_edition_unlimited" to "This price can't tell 1st Edition from Unlimited — they can differ by a lot. Check for the 1st Edition stamp before you sell.",
        )
    }

    public object EditionAmbiguityNoPriceLabels {
        public val all: Map<String, String> = mapOf(
            "first_edition_shadowless_unlimited" to "This card comes in 1st Edition, Shadowless and Unlimited printings, which differ by a lot. Check the stamp and the shadow.",
            "first_edition_unlimited" to "This card comes in 1st Edition and Unlimited printings, which differ by a lot. Check for the 1st Edition stamp.",
        )
    }

    public object SaleVenueLabels {
        public val all: Map<String, String> = mapOf(
            "ebay" to "eBay",
            "vinted" to "Vinted",
            "tcgplayer" to "TCGplayer",
            "cardmarket" to "Cardmarket",
            "whatnot" to "Whatnot",
            "facebook" to "Facebook",
            "show" to "Card show",
            "local" to "Local / cash",
            "buylist" to "Buylist",
            "trade" to "Trade",
            "other" to "Other",
        )
    }

    public object DispositionOnlyLabels {
        public val all: Map<String, String> = mapOf(
            "keep" to "Keep",
            "bundle" to "Bundle",
        )
    }

    public object ConditionLabels {
        public val all: Map<String, String> = mapOf(
            "NM" to "Near Mint (NM)",
            "LP" to "Lightly Played (LP)",
            "MP" to "Moderately Played (MP)",
            "HP" to "Heavily Played (HP)",
            "DMG" to "Damaged (DMG)",
            "Graded" to "Graded",
        )
    }

    public object PriceSourceLabels {
        public val all: Map<String, String> = mapOf(
            "ebay-uk-sold" to "UK sold",
            "cardmarket_proxy" to "CardTrader marketplace",
            "poketrace-ebay" to "US eBay reference",
            "pokemontcg-cardmarket" to "CardMarket trend",
            "pokemontcg-tcgplayer" to "US TCGplayer reference",
        )
    }

    public object ActionVerbs {
        public val all: Map<String, String> = mapOf(
            "confirmAndNext" to "Confirm and next",
            "addToInventory" to "Add to inventory",
            "retry" to "Retry",
            "cancel" to "Cancel",
            "edit" to "Edit",
            "save" to "Save",
        )
    }

    public object HonestyCaveats {
        public val all: Map<String, String> = mapOf(
            "gradeEvLowConfidence" to "rough estimate, not a sold comp",
            "gradeEvNormalConfidence" to "based on current graded asking prices, not sold comps",
            "conditionEstimateOnly" to "Condition estimate only — not professionally graded.",
        )
    }

    public object ErrorCopy {
        public val all: Map<String, String> = mapOf(
            "genericUnexpected" to "An unexpected error occurred. Your data is safe — try again or refresh the page.",
            "networkError" to "Network error — try again.",
            "couldNotLoadGames" to "Couldn't load games — try again.",
            "couldNotUpdate" to "Couldn't update — try again.",
            "couldNotConnect" to "Couldn't connect — check your internet connection and try again.",
            "couldNotLoadInventory" to "Couldn't load your inventory — try refreshing the page.",
            "saveFailed" to "Couldn't save — try again.",
            "couldNotAutofillAddress" to "Couldn't auto-fill from eBay — enter your address manually above.",
            "couldNotImport" to "Couldn't import right now.",
            "couldNotScoreListing" to "Couldn't score this listing — check buying settings.",
            "notSignedIn" to "Not signed in — reload and try again.",
            "identifyFailed" to "Couldn't identify this card yet — its photos may still be uploading, or try a clearer shot.",
            "recommendationLoadFailed" to "Couldn't load pricing — try again.",
            "repriceFailed" to "Couldn't reprice — try again.",
            "ebayUnreachable" to "Couldn't reach eBay — try again.",
        )
    }

    public object EmptyCopy {
        public val all: Map<String, String> = mapOf(
            "dashboardHome" to "Nothing here yet",
            "searchNoMatch" to "No cards match your search.",
            "acquisitionDetail" to "No cards linked to this acquisition.",
            "dashboardEmpty" to "No cards yet — add some to see your dashboard.",
            "bulkPublish" to "No cards ready to list",
            "showDetail" to "No cards allocated to this show",
            "bundleDetail" to "No cards in this bundle",
        )
    }
}
