// AUTO-GENERATED by scripts/gen-swift.mjs from src/strings.json — do not edit by hand.
// Regenerate via `npm run build`. See README.md "Releasing a new version".

import Foundation

public enum CurioCopy {
    public enum LegacyCardStatusLabels {
        public static let all: [String: String] = [
        "draft": "Draft",
        "in_stock": "In stock",
        "listed": "Listed",
        "sold": "Sold",
        "reconciled": "Reconciled",
        "returned": "Returned",
        "archived": "Archived",
    ]
    }
    public enum PhysicalCardLifecycleLabels {
        public static let all: [String: String] = [
        "NEEDS_ID_REVIEW": "Needs ID review",
        "NEEDS_CONDITION": "Needs condition",
        "NEEDS_DECISION": "Needs decision",
        "READY_TO_LIST": "Ready to list",
        "EBAY_DRAFT": "Draft created",
        "LISTED": "Listed",
    ]
    }
    public enum AttentionQueueCtas {
        public static let all: [String: String] = [
        "NEEDS_ID_REVIEW": "Review",
        "NEEDS_CONDITION": "Assess",
        "NEEDS_DECISION": "Decide",
        "READY_TO_LIST": "List",
    ]
    }
    public enum RouteLabels {
        public static let all: [String: String] = [
        "list_single": "List individually",
        "bundle": "Bundle",
        "bulk": "Bulk",
        "hold": "Hold",
        "grade_review": "Consider grading",
        "restoration_review": "Restoration review",
        "do_not_list": "Don't list",
    ]
    }
    public enum RouteReasonLabels {
        public static let all: [String: String] = [
        "below_bulk_floor": "Fees and postage absorb the value",
        "net_below_minimum": "Nets less than your minimum",
        "grade_worth_reviewing": "Worth checking graded comps",
        "thin_market": "Not enough recent sales to price it confidently",
        "bundle_lot_available": "You hold enough similar cards to make a lot",
        "sound_single_listing": "Sells well on its own",
    ]
    }
    public enum AlternativeReasonLabels {
        public static let all: [String: String] = [
        "net_negative_after_costs": "Net negative after fees and postage",
        "bundle_shares_postage": "Bundling shares one postage",
        "list_ungraded_instead": "List it ungraded instead",
        "list_now_accept_slower": "List now and accept a slower sale",
        "list_alone_instead": "List it on its own instead",
    ]
    }
    public enum DegradedReasonLabels {
        public static let all: [String: String] = [
        "no_sale_count": "No recent sales data to draw on",
        "fees_unknown": "Your fee settings weren't available",
        "compatible_count_unknown": "We didn't check your other cards",
    ]
    }
    public enum DecisionUnavailableLabels {
        public static let all: [String: String] = [
        "identity_unresolved": "We couldn't identify this card",
        "no_market_value": "No recent sales to price this from",
        "pricing_unavailable": "Pricing is unavailable right now — try again shortly",
    ]
    }
    public enum AssumptionLabels {
        public static let all: [String: String] = [
        "channel": "Assumed you'll sell on eBay",
        "seller_type": "Assumed you sell as a private seller",
        "vat_registered": "Assumed you're not VAT-registered",
        "condition": "Assumed near mint condition",
        "postage": "Assumed standard postage",
        "packaging": "Assumed standard packaging",
        "tax_rate": "Assumed the basic-rate tax band",
        "cost_basis": "Assumed you haven't bought it yet",
    ]
    }
    public enum EditionAmbiguityLabels {
        public static let all: [String: String] = [
        "first_edition_shadowless_unlimited": "This price can't tell 1st Edition, Shadowless and Unlimited apart — they can differ by a lot. Check the stamp and the shadow before you sell.",
        "first_edition_unlimited": "This price can't tell 1st Edition from Unlimited — they can differ by a lot. Check for the 1st Edition stamp before you sell.",
    ]
    }
    public enum ConditionLabels {
        public static let all: [String: String] = [
        "NM": "Near Mint (NM)",
        "LP": "Lightly Played (LP)",
        "MP": "Moderately Played (MP)",
        "HP": "Heavily Played (HP)",
        "DMG": "Damaged (DMG)",
        "Graded": "Graded",
    ]
    }
    public enum PriceSourceLabels {
        public static let all: [String: String] = [
        "ebay-uk-sold": "UK sold",
        "cardmarket_proxy": "CardTrader marketplace",
        "poketrace-ebay": "US eBay reference",
        "pokemontcg-cardmarket": "CardMarket trend",
        "pokemontcg-tcgplayer": "US TCGplayer reference",
    ]
    }
    public enum ActionVerbs {
        public static let all: [String: String] = [
        "confirmAndNext": "Confirm and next",
        "addToInventory": "Add to inventory",
        "retry": "Retry",
        "cancel": "Cancel",
        "edit": "Edit",
        "save": "Save",
    ]
    }
    public enum HonestyCaveats {
        public static let all: [String: String] = [
        "gradeEvLowConfidence": "rough estimate, not a sold comp",
        "gradeEvNormalConfidence": "based on current graded asking prices, not sold comps",
        "conditionEstimateOnly": "Condition estimate only — not professionally graded.",
    ]
    }
    public enum ErrorCopy {
        public static let all: [String: String] = [
        "genericUnexpected": "An unexpected error occurred. Your data is safe — try again or refresh the page.",
        "networkError": "Network error — try again.",
        "couldNotLoadGames": "Couldn't load games — try again.",
        "couldNotUpdate": "Couldn't update — try again.",
        "couldNotConnect": "Couldn't connect — check your internet connection and try again.",
        "couldNotLoadInventory": "Couldn't load your inventory — try refreshing the page.",
        "saveFailed": "Couldn't save — try again.",
        "couldNotAutofillAddress": "Couldn't auto-fill from eBay — enter your address manually above.",
        "couldNotImport": "Couldn't import right now.",
        "couldNotScoreListing": "Couldn't score this listing — check buying settings.",
        "notSignedIn": "Not signed in — reload and try again.",
        "identifyFailed": "Couldn't identify this card yet — its photos may still be uploading, or try a clearer shot.",
        "recommendationLoadFailed": "Couldn't load pricing — try again.",
        "repriceFailed": "Couldn't reprice — try again.",
        "ebayUnreachable": "Couldn't reach eBay — try again.",
    ]
    }
    public enum EmptyCopy {
        public static let all: [String: String] = [
        "dashboardHome": "Nothing here yet",
        "searchNoMatch": "No cards match your search.",
        "acquisitionDetail": "No cards linked to this acquisition.",
        "dashboardEmpty": "No cards yet — add some to see your dashboard.",
        "bulkPublish": "No cards ready to list",
        "showDetail": "No cards allocated to this show",
        "bundleDetail": "No cards in this bundle",
    ]
    }
}
