// Generates Sources/CurioCopy/Strings.swift from src/strings.json.
//
// DESIGN CHOICE (documented so a future edit doesn't "improve" this into something fragile):
// each group becomes a Swift enum with ONE `public static let all: [String: String]` dictionary —
// not one named `static let` constant per key. A per-key constant needs a snake_case/kebab-case/
// UPPER_SNAKE_CASE -> Swift-identifier conversion (status values come from the DB as raw strings
// like "NEEDS_ID_REVIEW"; route values as "list_single"; price sources as "ebay-uk-sold") which is
// exactly the kind of lossy, collision-prone mapping curio-contracts' zod-to-swift walker needs a
// full disambiguation scheme for. The real call site is always "I have this raw wire string, give
// me its label" (`CurioCopy.RouteLabels.all[route.rawValue]`), which a dictionary answers directly
// and correctly for every key with zero identifier-sanitization risk.
//
// USAGE: npm run build (also runs the TS build first)

import { writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import strings from "../src/strings.json" with { type: "json" };

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");
const outDir = process.env.CURIO_COPY_OUT_DIR ?? join(root, "Sources/CurioCopy");

function swiftStringLiteral(s) {
  return `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`;
}

function emitDict(entries) {
  const lines = Object.entries(entries)
    .filter(([k]) => !k.startsWith("$"))
    .map(([k, v]) => `        ${swiftStringLiteral(k)}: ${swiftStringLiteral(v)},`);
  return `[\n${lines.join("\n")}\n    ]`;
}

// Flat groups: { key: "label", ... } -> one enum with one `all` dict.
const FLAT_GROUPS = {
  LegacyCardStatusLabels: strings.statusLabels.legacyCardStatus,
  PhysicalCardLifecycleLabels: strings.statusLabels.physicalCardLifecycle,
  AttentionQueueCtas: strings.attentionQueueCtas,
  RouteLabels: strings.recommendationRouteLabels,
  RouteReasonLabels: strings.routeReasonLabels,
  AlternativeReasonLabels: strings.alternativeReasonLabels,
  DegradedReasonLabels: strings.degradedReasonLabels,
  DecisionUnavailableLabels: strings.decisionUnavailableLabels,
  AssumptionLabels: strings.assumptionLabels,   // add here AND in gen-kotlin.mjs — src/generated-coverage.test.ts enforces both
  ConditionLabels: strings.conditionLabels,
  PriceSourceLabels: strings.priceSourceLabels,
  ActionVerbs: strings.actionVerbs,
  HonestyCaveats: strings.honestyCaveats,
  ErrorCopy: strings.errorCopy,
  EmptyCopy: strings.emptyCopy,
};

let body = "";
for (const [name, entries] of Object.entries(FLAT_GROUPS)) {
  body += `    public enum ${name} {\n`;
  body += `        public static let all: [String: String] = ${emitDict(entries)}\n`;
  body += `    }\n`;
}

const out = `// AUTO-GENERATED by scripts/gen-swift.mjs from src/strings.json — do not edit by hand.
// Regenerate via \`npm run build\`. See README.md "Releasing a new version".

import Foundation

public enum CurioCopy {
${body}}
`;

mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, "Strings.swift"), out);
console.log(`Wrote ${join(outDir, "Strings.swift")}`);
