// Generates src/main/kotlin/com/curio/copy/Strings.kt from src/strings.json.
//
// A DIRECT MIRROR of gen-swift.mjs — same groups, same design choice, same order — so the two
// outputs cannot drift in shape. Added 2026-08-28 because @curio/copy had no Kotlin target at all,
// and Android was stubbing labels behind a single accessor precisely because it could not consume
// this package. iOS hit the same wall on the decision hero: with no English for the reason codes,
// it could not move off /api/recommend, and inventing the English client-side is what the contract
// forbids.
//
// The design choice is inherited deliberately: each group is an object with ONE
// `val all: Map<String, String>` rather than a named constant per key. Keys arrive as raw wire
// strings ("NEEDS_ID_REVIEW", "list_single", "ebay-uk-sold"), and converting those to Kotlin
// identifiers is a lossy, collision-prone mapping. The real call site is always "I have this raw
// string, give me its label", which a map answers directly.

import { writeFileSync, mkdirSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import strings from "../src/strings.json" with { type: "json" };

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");
const outDir = process.env.CURIO_COPY_KOTLIN_OUT_DIR ?? join(root, "src/main/kotlin/com/curio/copy");

function kotlinStringLiteral(s) {
  // Kotlin templates $ in string literals, which Swift does not — so this escapes one character
  // Swift's emitter does not have to. The rest is identical.
  return `"${s.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\$/g, "\\$")}"`;
}

function emitMap(entries) {
  const lines = Object.entries(entries)
    .filter(([k]) => !k.startsWith("$"))
    .map(([k, v]) => `            ${kotlinStringLiteral(k)} to ${kotlinStringLiteral(v)},`);
  return `mapOf(\n${lines.join("\n")}\n        )`;
}

// Identical list to gen-swift.mjs's FLAT_GROUPS, in the same order.
const FLAT_GROUPS = {
  LegacyCardStatusLabels: strings.statusLabels.legacyCardStatus,
  PhysicalCardLifecycleLabels: strings.statusLabels.physicalCardLifecycle,
  AttentionQueueCtas: strings.attentionQueueCtas,
  RouteLabels: strings.recommendationRouteLabels,
  RouteReasonLabels: strings.routeReasonLabels,
  AlternativeReasonLabels: strings.alternativeReasonLabels,
  DegradedReasonLabels: strings.degradedReasonLabels,
  DecisionUnavailableLabels: strings.decisionUnavailableLabels,
  AssumptionLabels: strings.assumptionLabels,
  EditionAmbiguityLabels: strings.editionAmbiguityLabels,
  EditionAmbiguityNoPriceLabels: strings.editionAmbiguityNoPriceLabels,   // add here AND in gen-swift.mjs — src/generated-coverage.test.ts enforces both
  SaleVenueLabels: strings.saleVenueLabels,
  DispositionOnlyLabels: strings.dispositionOnlyLabels,
  ConditionLabels: strings.conditionLabels,
  PriceSourceLabels: strings.priceSourceLabels,
  ActionVerbs: strings.actionVerbs,
  HonestyCaveats: strings.honestyCaveats,
  ErrorCopy: strings.errorCopy,
  EmptyCopy: strings.emptyCopy,
};

let body = "";
for (const [name, entries] of Object.entries(FLAT_GROUPS)) {
  body += `    public object ${name} {\n`;
  body += `        public val all: Map<String, String> = ${emitMap(entries)}\n`;
  body += `    }\n\n`;
}

const out = `// AUTO-GENERATED by scripts/gen-kotlin.mjs from src/strings.json — do not edit by hand.
// Regenerate via \`npm run build\`. See README.md "Releasing a new version".

package com.curio.copy

public object CurioCopy {
${body.trimEnd()}
}
`;

mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, "Strings.kt"), out);
console.log(`Wrote ${join(outDir, "Strings.kt")}`);
